import Head from "next/head";
import Layout from "~/components/Layout/Applayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Utkat's Assignment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  );
}
