import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-dark">
        <h1 className="bg-tertiary text-5xl font-bold text-white ">Meow</h1>
        <h1 className="bg-primary text-5xl font-bold text-white ">Meow</h1>

        <h1 className="bg-secondary text-5xl font-bold  text-white ">Meow</h1>
      </main>
    </>
  );
}
